### PR TITLE
Set priority grouping explicitly to 3.1(PRIO.SUBPRIO)

### PR DESCRIPTION
**Pull request by IhorNehrutsa**
1)Set STEP input filter to 0
2)Set priority grouping explicitly to 3.1(PRIO.SUBPRIO)
Default priority grouping is 2.2

### CODE REVIEW

**Comment by IhorNehrutsa** [comment]
https://github.com/CAP1Sup/Intellistep/blob/f292d5d595b82d5efa1879fca8f6c93d19482ed4/platformio.ini#L30-L32
>(set to zero for step interrupt) 

Is that right?

**Comment by CAP1Sup** [comment]
That's the only way to set it as far as I know. The PIO file is loaded first, then the project begins to build. There's a file that defines the priority unless this one is specified. I forget exactly what file it is, but I know it works

**Comment by IhorNehrutsa** [comment]
My question was about the "(set to zero for step interrupt)" and "-D EXTI_IRQ_PRIO=6"

**Comment by CAP1Sup** [comment]
> My question was about the comment "(set to zero for step interrupt)" and "-D EXTI_IRQ_PRIO=6"

Oh, sorry about that. I originally had it as `=0`. I realized that it would interfere with some of the regular needed interrupts. Sorry for the comment being left there, it's wrong.

**Comment by IhorNehrutsa** [comment]
Ready

**Pull request merged**
