### PR TITLE
Conversion of String to sprintf

### PR DESCRIPTION
**Pull request by TazerReloaded**
I converted the uses of the String class to C-style snprintf calls that always use the same buffer, so no memory allocations are required.
This should speed up the OLED updates a bit and prevent instability due to heap fragmentation.

I can't test this because my S42B is on the printer right now, but it should work. Maybe I messed up the padding somewhere.
If it works correctly I can adapt the serial and CAN sources too. Please test!

Does `writeOLEDString(0, 0, F("Intellistep"), false);` work as intended? If so, we should change every call to that function that uses static strings to using flash strings, which would further reduce memory usage.

### CODE REVIEW

**Comment by CAP1Sup** [comment]
I tested the code, but all I see are blank spaces where the numbers should be. The C for the temp is there though. I've never worked with sprintf, so I'm not exactly sure how to fix it and I cannot work on the boards until the weekend.

**Comment by TazerReloaded** [comment]
Hm, maybe a compiler flag is missing, the Arduino library has its own sprintf implementation with drastically reduced feature set. I'll have a look after work, should be an easy fix. Thank you for testing!

**Comment by CAP1Sup** [comment]
No problem! I'm just happy to have someone else helping on the code. I'll check it again after you fix it. Let me know when you're ready.

**Comment by TazerReloaded** [comment]
I found the missing compiler flag and added it in `platformio.ini`. Full float support uses around 5kb or 3.5% of additional flash space, that shouldn't be an issue.
I tested it on my driver, seems to work fine now. The values are jumping around a bit, but that also happens on upstream.

**Comment by TazerReloaded** [comment]
I also made some little adjustments to make it look like before and not jump around so much, once the numbers are constrained to a specific range we can use a shorter format again.

**Comment by CAP1Sup** [comment]
Excellent job! I'll make some changes so that you're recognized for the work.

**Pull request merged**
