### PR TITLE
Feature merge from TIM2 Master Record

### PR DESCRIPTION
**Pull request by CAP1Sup**
TIM2 is now set up as a hardware step counter. This ensures that there are no missed steps.

### CODE REVIEW

**Comment by xerootg** [comment]
I went through the tip of master and looked over tim2. It looks correct, one thing I did not see though, was disabling the counter when enable is low?

**Comment by xerootg** [comment]
Also, we need to keep an eye on noise. If we start seeing goofy counts, we may need to implement the filter that is mentioned in the docs for debouncing/etc. The coolest part of using this hardware counter is the stupid insane speed at which we can now count. Hardware peripherals for the win! ;)

**Comment by CAP1Sup** [comment]
> I went through the tip of master and looked over tim2. It looks correct, one thing I did not see though, was disabling the counter when enable is low?

I instead just set TIM2 to the closest step to the current angle the next time the board enables. The board then behaves just like a regular stepper

**Comment by CAP1Sup** [comment]
I haven't really seen any problems with noise so far. I think I did set a filter (same one BTT had) on the step pin, but I'm not sure.

**Pull request merged**
