### PR TITLE
Check encoder speed

### PR DESCRIPTION
**Pull request by IhorNehrutsa**
34.8kHz

### CODE REVIEW

**Comment by CAP1Sup** [comment]
So based on the fact that performance is slower with the encoder, I was thinking that maybe the dynamic current control only samples like every other time or every 3rd or 4th time? Realistically we're not going to need to update the acceleration that much.

**Comment by IhorNehrutsa** [comment]
We need fast encoder for PID.

**Comment by CAP1Sup** [comment]
I know, it's just that I don't know how to speed it up. Maybe we could try higher communication frequencies, but I'm not sure that they would work

**Comment by IhorNehrutsa** [comment]
I have a few little ideas...

**Comment by IhorNehrutsa** [comment]
You may merge it.

**Pull request merged**
