### PR TITLE
Zero the encoder after the motor is enabled

### PR DESCRIPTION
**Pull request by IhorNehrutsa**
The motor has a small jump(move) after being powered on.

### CODE REVIEW

**Comment by CAP1Sup** [comment]
I think that we should wait to enable the motor until the enable pin is triggered

**Comment by IhorNehrutsa** [comment]
This needs a test

**Comment by IhorNehrutsa** [comment]
I think that disable-enable the motor is not good idea. That leads jumps when reset. There is EN pin for control the motor. I think   the init state for motor may be COAST(IDLE)

**Comment by CAP1Sup** [comment]
Alright then, is this ready for merge?

**Comment by IhorNehrutsa** [comment]
Yes

**Pull request merged**
