### PR TITLE
motor.step() uses a direct value stepChange instead of a flag useMultiplier

### PR DESCRIPTION
**Pull request by IhorNehrutsa**

### CODE REVIEW

**Comment by CAP1Sup** [comment]
The microstep multiplier shouldn't be public. It should be retrieved with the function `getMicrostepMultiplier()`

**Comment by IhorNehrutsa** [comment]
getMicrostepMultiplier() needs  more time. I do not see a problem with a public microstepMultiplier

**Comment by CAP1Sup** [comment]
Is there a way to make it publicly readable but only locally writable? That would allow for faster access but prevent writing if we needed to do something when the multiplier changed

**Comment by CAP1Sup** [comment]
Ready for merge?

**Comment by IhorNehrutsa** [comment]
I have tested public and private microstepMultiplier.
The private is much slowly.

**Pull request merged**
